# Generated by Django 4.2 on 2023-04-28 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_rename_name_user_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="username",
            new_name="name",
        ),
    ]
